window.FANTASY_PLAYERS = [
  { name: "Jahmyr Gibbs", position: "RB", team: "DET", value: 100, tier: "Elite" },
  { name: "Bijan Robinson", position: "RB", team: "ATL", value: 99, tier: "Elite" },
  { name: "Ja'Marr Chase", position: "WR", team: "CIN", value: 99, tier: "Elite" },
  { name: "Puka Nacua", position: "WR", team: "LAR", value: 98, tier: "Elite" },
  { name: "Amon-Ra St. Brown", position: "WR", team: "DET", value: 97, tier: "Elite" },
  { name: "Jaxon Smith-Njigba", position: "WR", team: "SEA", value: 96, tier: "Elite" },
  { name: "Christian McCaffrey", position: "RB", team: "SF", value: 95, tier: "Elite" },
  { name: "Jonathan Taylor", position: "RB", team: "IND", value: 95, tier: "Elite" },
  { name: "CeeDee Lamb", position: "WR", team: "DAL", value: 94, tier: "Elite" },
  { name: "Justin Jefferson", position: "WR", team: "MIN", value: 93, tier: "Elite" },

  { name: "Brock Bowers", position: "TE", team: "LV", value: 93, tier: "Elite TE Premium", tePremium: true },
  { name: "Trey McBride", position: "TE", team: "ARI", value: 91, tier: "Elite TE Premium", tePremium: true },

  { name: "James Cook", position: "RB", team: "BUF", value: 91, tier: "Elite" },
  { name: "Saquon Barkley", position: "RB", team: "PHI", value: 90, tier: "Elite" },
  { name: "Kenneth Walker III", position: "RB", team: "SEA", value: 89, tier: "High-End Starter" },
  { name: "Chase Brown", position: "RB", team: "CIN", value: 88, tier: "High-End Starter" },
  { name: "Nico Collins", position: "WR", team: "HOU", value: 88, tier: "High-End Starter" },
  { name: "Drake London", position: "WR", team: "ATL", value: 87, tier: "High-End Starter" },
  { name: "De'Von Achane", position: "RB", team: "MIA", value: 86, tier: "High-End Starter" },
  { name: "Chris Olave", position: "WR", team: "NO", value: 85, tier: "High-End Starter" },
  { name: "George Pickens", position: "WR", team: "DAL", value: 84, tier: "High-End Starter" },
  { name: "A.J. Brown", position: "WR", team: "PHI", value: 83, tier: "High-End Starter" },
  { name: "Malik Nabers", position: "WR", team: "NYG", value: 82, tier: "High-End Starter" },
  { name: "DeVonta Smith", position: "WR", team: "PHI", value: 81, tier: "High-End Starter" },
  { name: "Omarion Hampton", position: "RB", team: "LAC", value: 80, tier: "High-End Starter" },
  { name: "Derrick Henry", position: "RB", team: "BAL", value: 79, tier: "High-End Starter" },
  { name: "Ashton Jeanty", position: "RB", team: "LV", value: 78, tier: "High-End Starter" },
  { name: "Garrett Wilson", position: "WR", team: "NYJ", value: 77, tier: "High-End Starter" },
  { name: "Jaylen Waddle", position: "WR", team: "MIA", value: 76, tier: "High-End Starter" },
  { name: "Tee Higgins", position: "WR", team: "CIN", value: 75, tier: "High-End Starter" },
  { name: "Zay Flowers", position: "WR", team: "BAL", value: 74, tier: "High-End Starter" },
  { name: "Rashee Rice", position: "WR", team: "KC", value: 73, tier: "High-End Starter" },

  { name: "Colston Loveland", position: "TE", team: "CHI", value: 79, tier: "High-End TE Premium", tePremium: true },
  { name: "Tyler Warren", position: "TE", team: "IND", value: 77, tier: "High-End TE Premium", tePremium: true },
  { name: "Sam LaPorta", position: "TE", team: "DET", value: 76, tier: "High-End TE Premium", tePremium: true },
  { name: "Tucker Kraft", position: "TE", team: "GB", value: 75, tier: "High-End TE Premium", tePremium: true },
  { name: "George Kittle", position: "TE", team: "SF", value: 74, tier: "High-End TE Premium", tePremium: true },

  { name: "Ladd McConkey", position: "WR", team: "LAC", value: 74, tier: "High-End Starter" },
  { name: "Breece Hall", position: "RB", team: "NYJ", value: 73, tier: "High-End Starter" },
  { name: "Kyren Williams", position: "RB", team: "LAR", value: 72, tier: "High-End Starter" },
  { name: "Javonte Williams", position: "RB", team: "DAL", value: 71, tier: "Quality Starter" },
  { name: "Tetairoa McMillan", position: "WR", team: "CAR", value: 70, tier: "Quality Starter" },
  { name: "Emeka Egbuka", position: "WR", team: "TB", value: 69, tier: "Quality Starter" },
  { name: "Luther Burden III", position: "WR", team: "CHI", value: 68, tier: "Quality Starter" },
  { name: "Christian Watson", position: "WR", team: "GB", value: 67, tier: "Quality Starter" },
  { name: "Rome Odunze", position: "WR", team: "CHI", value: 66, tier: "Quality Starter" },
  { name: "Davante Adams", position: "WR", team: "LAR", value: 65, tier: "Quality Starter" },
  { name: "Bucky Irving", position: "RB", team: "TB", value: 64, tier: "Quality Starter" },
  { name: "Terry McLaurin", position: "WR", team: "WAS", value: 63, tier: "Quality Starter" },
  { name: "Rhamondre Stevenson", position: "RB", team: "NE", value: 62, tier: "Quality Starter" },
  { name: "TreVeyon Henderson", position: "RB", team: "NE", value: 61, tier: "Quality Starter" },
  { name: "Marvin Harrison Jr.", position: "WR", team: "ARI", value: 60, tier: "Quality Starter" },
  { name: "Josh Allen", position: "QB", team: "BUF", value: 60, tier: "Elite QB" },
  { name: "Lamar Jackson", position: "QB", team: "BAL", value: 59, tier: "Elite QB" },
  { name: "Jalen Hurts", position: "QB", team: "PHI", value: 58, tier: "Elite QB" },
  { name: "Jayden Daniels", position: "QB", team: "WAS", value: 57, tier: "Elite QB" },

  { name: "Harold Fannin Jr.", position: "TE", team: "CLE", value: 66, tier: "TE Premium Starter", tePremium: true },
  { name: "Kyle Pitts", position: "TE", team: "ATL", value: 63, tier: "TE Premium Starter", tePremium: true },
  { name: "Dalton Kincaid", position: "TE", team: "BUF", value: 62, tier: "TE Premium Starter", tePremium: true },
  { name: "Travis Kelce", position: "TE", team: "KC", value: 61, tier: "TE Premium Starter", tePremium: true },
  { name: "Mark Andrews", position: "TE", team: "BAL", value: 58, tier: "TE Premium Starter", tePremium: true },
  { name: "Dallas Goedert", position: "TE", team: "PHI", value: 49, tier: "TE Premium Starter", tePremium: true },
  { name: "Isaiah Likely", position: "TE", team: "BAL", value: 47, tier: "TE Premium Starter", tePremium: true },
  { name: "Juwan Johnson", position: "TE", team: "NO", value: 44, tier: "TE Premium Starter", tePremium: true },
  { name: "Jake Ferguson", position: "TE", team: "DAL", value: 43, tier: "TE Premium Starter", tePremium: true },
  { name: "Hunter Henry", position: "TE", team: "NE", value: 40, tier: "TE Premium Starter", tePremium: true }
];
